project:
  type: website

website:
  title: "my_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/elie-chataigner-8a1271230/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

